"""List of RSS feeds to add to the RSS reader."""

from __future__ import annotations

rss_feeds: list[str] = [
    "https://www.svt.se/kultur/rss.xml",
    "https://www.svt.se/nyheter/amne/svt-nyheter-verifierar-krigets-bilder/rss.xml",
    "https://www.svt.se/nyheter/ekonomi/rss.xml",
    "https://www.svt.se/nyheter/granskning/rss.xml",
    "https://www.svt.se/nyheter/inrikes/rss.xml",
    "https://www.svt.se/nyheter/lokalt/blekinge/rss.xml",
    "https://www.svt.se/nyheter/lokalt/dalarna/rss.xml",
    "https://www.svt.se/nyheter/lokalt/gavleborg/rss.xml",
    "https://www.svt.se/nyheter/lokalt/halland/rss.xml",
    "https://www.svt.se/nyheter/lokalt/helsingborg/rss.xml",
    "https://www.svt.se/nyheter/lokalt/jamtland/rss.xml",
    "https://www.svt.se/nyheter/lokalt/jonkoping/rss.xml",
    "https://www.svt.se/nyheter/lokalt/norrbotten/rss.xml",
    "https://www.svt.se/nyheter/lokalt/orebro/rss.xml",
    "https://www.svt.se/nyheter/lokalt/ost/rss.xml",
    "https://www.svt.se/nyheter/lokalt/skane/rss.xml",
    "https://www.svt.se/nyheter/lokalt/smaland/rss.xml",
    "https://www.svt.se/nyheter/lokalt/sodertalje/rss.xml",
    "https://www.svt.se/nyheter/lokalt/sormland/rss.xml",
    "https://www.svt.se/nyheter/lokalt/stockholm/rss.xml",
    "https://www.svt.se/nyheter/lokalt/uppsala/rss.xml",
    "https://www.svt.se/nyheter/lokalt/varmland/rss.xml",
    "https://www.svt.se/nyheter/lokalt/vast/rss.xml",
    "https://www.svt.se/nyheter/lokalt/vast/rss.xml",
    "https://www.svt.se/nyheter/lokalt/vasterbotten/rss.xml",
    "https://www.svt.se/nyheter/lokalt/vasternorrland/rss.xml",
    "https://www.svt.se/nyheter/lokalt/vastmanland/rss.xml",
    "https://www.svt.se/nyheter/nyhetstecken/rss.xml",
    "https://www.svt.se/nyheter/sapmi/rss.xml",
    "https://www.svt.se/nyheter/svtforum/rss.xml",
    "https://www.svt.se/nyheter/utrikes/rss.xml",
    "https://www.svt.se/nyheter/uutiset/rss.xml",
    "https://www.svt.se/nyheter/vetenskap/rss.xml",
    "https://www.svt.se/rss.xml",
    "https://www.svt.se/sport/rss.xml",
    "https://www.svt.se/vader/rss.xml",
]
